
POST  http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "Binh5456ee",
  "password":"123456"
}

###  get by page


GET   http://localhost:5000/product/?page=1
Content-Type: application/json

####  @@@@get by id
GET   http://localhost:5000/product/detail/?id=629b2f7244cdb5374d016f69

Content-Type: application/json

#### @@@@@@@ get by name

GET   http://localhost:5000/product/search/?name=short


Content-Type: application/json

